services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timedb
      MYSQL_USER: example
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql/  
  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile   
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf